### ISSUE TITLE
File receiving very slow with nexmon (packet injection broken?)

### ISSUE THREAD

**Issue by Eco-Gaming** [bodaay/GoOpenDrop#11]
(I slightly modified the code to run OWL with the command `"owl", "-i", wlanDevName, "-h", OwlName, "-N"` instead of `"owl", "-i", wlanDevName, "-h", OwlName, "-c", owlChannel`, however I can't see this being the reason for my problem)

Whenever I receive a file over AirDrop from multiple different iOS devices (iPhone 6 (iOS 12.5.5) and iPad Pro 3rd Gen (iOS 16.3.1)), it takes a while for GoOpenDrop to accept the request and afterwards sending takes forever.

For example, a 5MB file which i can receive with opendrop on my MacBook Pro 2012 (running macOS Ventura with OpenCore) in 1 second takes multiple minutes to receive with GoOpenDrop.

I'm using a Raspberry Pi 3 with the integrated WiFi module patched with nexmon and my [fork](https://github.com/Eco-Gaming/GoOpenDrop) of GoOpenDrop, but as stated above I doubt that's where my problem is coming from.

A few days ago I had [opendrop](https://github.com/seemoo-lab/opendrop) running on my Pi with [owl](https://github.com/seemoo-lab/owl) and receiving was just as fast as it is now on my MacBook. I can't replicate this anymore as my Apple devices just don't find my Raspberry Pi with opendrop anymore, likely due to the absence of BLE.

Given the slow speeds and that it worked with opendrop, I'm assuming the problem has to do with GoOpenDrop not doing the packet injection properly for the Apple device to know that it received the datachunk, but I don't know much about how opendrop works so I have no idea how to fix that.

Some parts of packet injection do work properly though, as when sending does finally complete, the Apple devices displays "Sent", meaning it knows the file was received by GoOpenDrop.

**Comment by bodaay** [comment]
I do think its because of nexamon, since it will not be properly Acknowledging the packets

Try with one of the supported adapters and see if there any difference

**Comment by Eco-Gaming** [comment]
You're probably right, I was pretty frustrated when I wrote that, been working on airdrop on my pi for a week and nothing is working.
I've pretty much completely given up on that (airdrop on pi) and I don't have any other WiFi adapters that support packet injection, so I can't try that right now, although I might look into it again later when I'm motivated again.

Until then I'd keep the issue open, in case anyone else tries using your project with nexmon and maybe has similar problems or even finds a solution.
