### ISSUE TITLE
Raspberry Pi Zero W 1.1 shows error

### ISSUE THREAD

**Issue by IronBit-0** [bodaay/GoOpenDrop#3]
after running `./Build_Pi.sh` to set up,
running `sudo ./goopendrop ./config.json` in `~/GoOpenDrop/out/arm` returns `Illegal instruction`
running `sudo ./goopendrop ./config.json` in `~/GoOpenDrop/out/arm64` returns `./goopendrop: 4: Syntax error: Unterminated quoted string`
`go version` is `go version go1.19.2 linux/arm`, `uname -r` is `5.15.61+`.
I know that it's not built the Pi Zero W, but I wanted to try it out anyway.
Love what you're doing. Keep it up!

**Comment by bodaay** [comment]
do you know if you are using 32 bit raspbian or 64 bit?

one thing you could try, in Build_PI, change parameter:
GOARM=7
to
GOARM=5

**Comment by IronBit-0** [comment]
I am using Raspbian OS Lite 32. I replaced GOARM=7 with GOARM=5 in Build_Pi.sh, and it successfully built! It took ~25 minutes to build for each arm and arm64, which was a bit disconcerting as there is no output indicating that the program is doing anything, so it seems like the program is stuck or something.

Running from `~/GoOpenDrop/out/arm64` still returns `./goopendrop: 4: Syntax error: Unterminated quoted string`, but running in `~/GoOpenDrop/out/arm` runs successfully.

I used [The Even Better Way from this article](https://www.e-tinkers.com/2019/06/better-way-to-install-golang-go-on-raspberry-pi/) to install go. (For future reference)

**Comment by lucasromeiro** [comment]
> after running `./Build_Pi.sh` to set up, running `sudo ./goopendrop ./config.json` in `~/GoOpenDrop/out/arm` returns `Illegal instruction` running `sudo ./goopendrop ./config.json` in `~/GoOpenDrop/out/arm64` returns `./goopendrop: 4: Syntax error: Unterminated quoted string` `go version` is `go version go1.19.2 linux/arm`, `uname -r` is `5.15.61+`. I know that it's not built the Pi Zero W, but I wanted to try it out anyway. Love what you're doing. Keep it up!

@IronBit-0 and @bodaay 
Hello everything is fine?
I'm with raspberry and I'm having a problem similar to yours.
Can you help me?
Were you able to successfully use the software on the raspberry?

I'm trying to use it on a raspberry zero 2.

But I have this problem:

I was able to run Build_Pi_Arm5.sh :


![image](https://user-images.githubusercontent.com/2086543/220224015-2a7896b1-570d-4985-a625-986e8a49275b.png)


But running config.json this happens:

![image](https://user-images.githubusercontent.com/2086543/220224033-da238a26-b0d3-45fe-b78f-f0b8b90977bf.png)



Can you help me?

Thank you very much

**Comment by lucasromeiro** [comment]
it ran, but this happened, it is stuck there...

![image](https://user-images.githubusercontent.com/2086543/220351735-43d706b6-e8f4-46a9-9f56-aa749653da6c.png)
