### ISSUE TITLE
Any way of using without expensive keys?

### ISSUE THREAD

**Issue by twoexem** [bodaay/GoOpenDrop#6]
**Is your feature request related to a problem? Please describe.**
Is there any way to not use the keys, e.g. by using a flag or doing something similar?

**Additional context**
The developer certificate needed for extracting keys requires a yearly fee of 99$

**Comment by bodaay** [comment]
Are you sure you cannot get it with a free developer account? my friend who extracted the keys for me said he did it with a free developer account, he has a paid account, but he created another one for key extraction. I need to confirm this with him again

**Comment by twoexem** [comment]
Well, I need a developer certificate for that, and those require a yearly fee, as far as I can tell. I'm by no means an Apple expert and could be wrong, but I don't see any free option.

**Comment by twoexem** [comment]
Will there be any update to this?

**Comment by PhilDevProg** [comment]
@bodaay Did you ask your friend?

**Comment by lucasromeiro** [comment]
@bodaay @PhilDevProg news? please, help us.

**Comment by lucasromeiro** [comment]
Guys, I'm having trouble extracting keys from my Mac Studio.  did you have any problems?  
can you give me any tips?  

thank you for any help.


![](https://user-images.githubusercontent.com/2086543/219902639-b89ad8e7-b088-48ee-a06f-236f4c51b2e5.png)

**Comment by lucasromeiro** [comment]
@bodaay @PhilDevProg @twoexem 
Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...

**Comment by twoexem** [comment]
I can't help you, sorry. I stopped trying since I don't need compability to Crapple's services anymore, and I don't own any of their devices to test stuff. I'll keep the issue open as others probably still need a solution to the certificate issue.

**Comment by lucasromeiro** [comment]
> 

Hi, thanks anyway for the reply.
I am unable to extract these keys to be able to proceed... =(

**Comment by twoexem** [comment]
I didn't succeed either with the Macbook from a relative, and I haven't tried again. Something with permissions not working correctly, I think.

**Comment by lucasromeiro** [comment]
> Também não consegui com o Macbook de um parente e não tentei novamente. Algo com permissões não está funcionando corretamente, eu acho.

I'll try to change the command to put enable...

**Comment by imashoksundar** [comment]
Hi, 
I had issues extracting keys following this readme file https://github.com/seemoo-lab/airdrop-keychain-extractor.  After investigating for a while I found out that SIP was not disabled properly (even after a reboot).

I was able to extract the keys following this approach to disable SIP temporarily and re-enable it after key extraction. 
https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection.

FYI:
I was using macOS Big Sur 11.0 and the free developer account which comes with limited access. 
More on this in this link https://www.idownloadblog.com/2015/12/24/how-to-create-a-free-apple-developer-account-xcode/

**Comment by lucasromeiro** [comment]
> Olá, tive problemas para extrair chaves seguindo este arquivo leia-me https://github.com/seemoo-lab/airdrop-keychain-extractor . Depois de investigar por um tempo, descobri que o SIP não foi desativado corretamente (mesmo após uma reinicialização).
> 
> Consegui extrair as chaves seguindo essa abordagem para desabilitar o SIP temporariamente e reativá-lo após a extração da chave. https://developer.apple.com/documentation/security/disabling_and_enabling_system_integrity_protection .
> 
> FYI: Eu estava usando o macOS Big Sur 11.0 e a conta de desenvolvedor gratuita que vem com acesso limitado. Mais sobre isso neste link https://www.idownloadblog.com/2015/12/24/how-to-create-a-free-apple-developer-account-xcode/

Thanks! 
Were you able to successfully use this library to send something to an apple device?

**Comment by imashoksundar** [comment]
Yes, we we're able to send files. What is the issue are you facing now?

**Comment by lucasromeiro** [comment]
> Yes, we we're able to send files. What is the issue are you facing now?

@imashoksundar 
Hello, thanks for the reply.
I have another open issue about this.
I have received great help.
But I don't know if I'm going in the right direction.
My problem is here:

![image](https://user-images.githubusercontent.com/2086543/221357209-c62fc853-fb9e-4ce4-9ea2-7f6bc5cb5091.png)

I was instructed that OWL would not be running.
I even bought a usb wifi dongle but nothing has changed yet.
My complete problem is here:

https://github.com/bodaay/GoOpenDrop/issues/10


I'm very grateful if you can help me
