### ISSUE TITLE
key extraction

### ISSUE THREAD

**Issue by lucasromeiro** [bodaay/GoOpenDrop#9]
Hello, I have a problem with the MAKE command step.

**Comment by lucasromeiro** [comment]
Hello everyone, this happened in the first step to get the keys:

![image](https://user-images.githubusercontent.com/2086543/220122693-248d8527-7e56-4ffd-805a-50d6554b6e27.png)


I continued the tutorial normally, but when I run the make command I get this error:

![image](https://user-images.githubusercontent.com/2086543/220122869-6bb240a3-a9cc-489c-8232-8946c903fa0f.png)


Can someone help me?

My MAC is a MacStudio with M1 Max and MAC OS 13.1 (22C65) (ventura).


Please, help...

**Comment by PhilDevProg** [comment]
In the first command `sudo` isn't found. Is your user the administrator? If not, you have to login as the Administrator of the Mac.

**Comment by lucasromeiro** [comment]
> In the first command `sudo` isn't found. Is your user the administrator? If not, you have to login as the Administrator of the Mac. If that doesn't help, your PATH environment variable might broken. Look here: https://discussions.apple.com/thread/8653929

Thanks for the feedback, in this case of SUDO I typed the wrong command, please disregard this command. I was supposed to type the first command in the tutorial and I ended up typing the second... The command I'm referring to in the print you looked at is the command: CSRUTIL....

**Comment by PhilDevProg** [comment]
csrutil enable --without nvram has to be run in macOS Recovery Mode and sudo nvram boot-args="amfi_get_out_of_my_way=1" after a reboot in the normal terminal. Did you do that correctly?

**Comment by lucasromeiro** [comment]
> csrutil enable --without nvram has to be run in macOS Recovery Mode and sudo nvram boot-args="amfi_get_out_of_my_way=1" after a reboot in the normal terminal. Did you do that correctly?

Exactly, I did it right! The first command was from recovery mode and the others were from normal mode.

**Comment by PhilDevProg** [comment]
This is weird... The README says it's `crsutil enable` while every other guide on the internet says it should be `csrutil disable`... Sorry, I can't help

**Comment by lucasromeiro** [comment]
> This is weird... The README says it's `crsutil enable` while every other guide on the internet says it should be `csrutil disable`... Sorry, I can't help

I'll try to change the command to put enable...

**Comment by PhilDevProg** [comment]
> I just tried it, looks like it ALMOST worked, --WITHOUT error occurred. I don't know why that....

Probably because --without is only made to work with enable. Maybe try it without --without nvram?

**Comment by lucasromeiro** [comment]
> > I just tried it, looks like it ALMOST worked, --WITHOUT error occurred. I don't know why that....
> 
> Probably because --without is only made to work with enable. Maybe try it without --without nvram?

I managed to extract the keys!!  thanks for the help, you were right.  at the end of the I needed to adjust my developer certificate which was a user and not an administrator.


now i have just installed ubuntu on a raspberry pi for you to use.  however, I still don't understand how to install and operate this code… I intend to use python to use it, could you give me any tips on how to install and use it?  the tutorial is a bit confusing for me.
